export enum KeyCode {
    // Teclas de controle
    Backspace = "Backspace",
    Tab = "Tab",
    Enter = "Enter",
    Shift = "Shift",
    Ctrl = "Control",
    Alt = "Alt",
    Pause = "Pause",
    CapsLock = "CapsLock",
    Esc = "Escape",
    Space = " ",
    Insert = "Insert",
    Delete = "Delete",
    Meta = "Meta",
    ContextMenu = "ContextMenu",

    // Navegação
    PageUp = "PageUp",
    PageDown = "PageDown",
    End = "End",
    Home = "Home",
    Left = "ArrowLeft",
    Up = "ArrowUp",
    Right = "ArrowRight",
    Down = "ArrowDown",

    // Função
    F1 = "F1",
    F2 = "F2",
    F3 = "F3",
    F4 = "F4",
    F5 = "F5",
    F6 = "F6",
    F7 = "F7",
    F8 = "F8",
    F9 = "F9",
    F10 = "F10",
    F11 = "F11",
    F12 = "F12",

    // Bloco numérico
    NumLock = "NumLock",
    ScrollLock = "ScrollLock",

    // Alfanumérico
    Key0 = "0",
    Key1 = "1",
    Key2 = "2",
    Key3 = "3",
    Key4 = "4",
    Key5 = "5",
    Key6 = "6",
    Key7 = "7",
    Key8 = "8",
    Key9 = "9",
    A = "a",
    B = "b",
    C = "c",
    D = "d",
    E = "e",
    F = "f",
    G = "g",
    H = "h",
    I = "i",
    J = "j",
    K = "k",
    L = "l",
    M = "m",
    N = "n",
    O = "o",
    P = "p",
    Q = "q",
    R = "r",
    S = "s",
    T = "t",
    U = "u",
    V = "v",
    W = "w",
    X = "x",
    Y = "y",
    Z = "z",

    // Símbolos
    Semicolon = ";",
    Equal = "=",
}
